import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "JanaByte - платформа для компьютерных клубов",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex py-5 border-b dark:border-[#363636]">
            <div className='w-[70%] mx-auto flex items-center'>
                <Image
                    className=""
                    src="/images/logo.svg"
                    alt="JanaByte Logo"
                    width={150}
                    height={50}
                    priority
                />
                <input
                    type='text'
                    placeholder='Поиск...'
                    className='ml-10 px-5 rounded-lg bg-black border-[#363636] border py-1'
                />
            </div>
        </div>
        <div className="flex">
            <div className='w-[70%] mx-auto'>
                {children}
            </div>
        </div>
      </body>
    </html>
  );
}
